package me.leolin.twse.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.leolin.twse.data.SubscriptionSetEntity;
import me.leolin.twse.data.SubscriptionEntity;

import me.leolin.twse.data.SubscriptionSetEntityDao;
import me.leolin.twse.data.SubscriptionEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig subscriptionSetEntityDaoConfig;
    private final DaoConfig subscriptionEntityDaoConfig;

    private final SubscriptionSetEntityDao subscriptionSetEntityDao;
    private final SubscriptionEntityDao subscriptionEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        subscriptionSetEntityDaoConfig = daoConfigMap.get(SubscriptionSetEntityDao.class).clone();
        subscriptionSetEntityDaoConfig.initIdentityScope(type);

        subscriptionEntityDaoConfig = daoConfigMap.get(SubscriptionEntityDao.class).clone();
        subscriptionEntityDaoConfig.initIdentityScope(type);

        subscriptionSetEntityDao = new SubscriptionSetEntityDao(subscriptionSetEntityDaoConfig, this);
        subscriptionEntityDao = new SubscriptionEntityDao(subscriptionEntityDaoConfig, this);

        registerDao(SubscriptionSetEntity.class, subscriptionSetEntityDao);
        registerDao(SubscriptionEntity.class, subscriptionEntityDao);
    }
    
    public void clear() {
        subscriptionSetEntityDaoConfig.getIdentityScope().clear();
        subscriptionEntityDaoConfig.getIdentityScope().clear();
    }

    public SubscriptionSetEntityDao getSubscriptionSetEntityDao() {
        return subscriptionSetEntityDao;
    }

    public SubscriptionEntityDao getSubscriptionEntityDao() {
        return subscriptionEntityDao;
    }

}
