package me.leolin.twse.data;

import java.util.List;
import me.leolin.twse.data.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SUBSCRIPTION_SET_ENTITY.
 */
public class SubscriptionSetEntity {

    private Long id;
    private String name;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SubscriptionSetEntityDao myDao;

    private List<SubscriptionEntity> subscriptionEntityList;

    public SubscriptionSetEntity() {
    }

    public SubscriptionSetEntity(Long id) {
        this.id = id;
    }

    public SubscriptionSetEntity(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSubscriptionSetEntityDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<SubscriptionEntity> getSubscriptionEntityList() {
        if (subscriptionEntityList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SubscriptionEntityDao targetDao = daoSession.getSubscriptionEntityDao();
            List<SubscriptionEntity> subscriptionEntityListNew = targetDao._querySubscriptionSetEntity_SubscriptionEntityList(id);
            synchronized (this) {
                if(subscriptionEntityList == null) {
                    subscriptionEntityList = subscriptionEntityListNew;
                }
            }
        }
        return subscriptionEntityList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetSubscriptionEntityList() {
        subscriptionEntityList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
