package me.leolin.twse.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SUBSCRIPTION_ENTITY.
 */
public class SubscriptionEntity {

    private String stockId;
    private Integer order;
    private Long setId;

    public SubscriptionEntity() {
    }

    public SubscriptionEntity(String stockId) {
        this.stockId = stockId;
    }

    public SubscriptionEntity(String stockId, Integer order, Long setId) {
        this.stockId = stockId;
        this.order = order;
        this.setId = setId;
    }

    public String getStockId() {
        return stockId;
    }

    public void setStockId(String stockId) {
        this.stockId = stockId;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Long getSetId() {
        return setId;
    }

    public void setSetId(Long setId) {
        this.setId = setId;
    }

}
